# Generated by Django 3.2.6 on 2021-08-27 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('min_value', models.FloatField()),
                ('qtd_hours', models.IntegerField()),
                ('percentage', models.FloatField()),
                ('bedroom_hour', models.IntegerField()),
                ('bedroom_hour_price', models.FloatField()),
                ('living_room_hour', models.IntegerField()),
                ('living_room_hour_price', models.FloatField()),
                ('bathroom_hour', models.IntegerField()),
                ('bathroom_hour_price', models.FloatField()),
                ('kitchen_hour', models.IntegerField()),
                ('kitchen_hour_price', models.FloatField()),
                ('yard_hour', models.IntegerField()),
                ('yard_hour_price', models.FloatField()),
                ('others_hour', models.IntegerField()),
                ('others_hour_price', models.FloatField()),
                ('icon', models.CharField(choices=[('twf-cleaning-1', 'twf-cleaning-1'), ('twf-cleaning-2', 'twf-cleaning-2'), ('twf-cleaning-3', 'twf-cleaning-3')], max_length=14)),
                ('position', models.IntegerField()),
            ],
        ),
    ]
